os:
  - linux

# TODO: one day when container infrastructure works better change to
# sudo: false
sudo: required

cache: apt

before_install:
    - sudo apt-add-repository -y ppa:opencog-dev/ppa
    - sudo apt-add-repository -y ppa:boost-latest/ppa
    - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update
    - wget -O setup.sh https://raw.githubusercontent.com/opencog/opencog/master/scripts/ocpkg
    - chmod +x setup.sh
    - export CXX="g++-4.9" CC="gcc-4.9"

install:
    - sudo apt-get install -y boost1.54 cxxtest cmake gcc-4.9 g++-4.9
    - sudo ./setup.sh -c

before_script:
    - mkdir build
    - cd build
    - cmake ..

script:
    - make -j$(nproc)
    - make examples
    - make tests
    - make test
